### ISSUE TITLE
Adding new discount types

### ISSUE THREAD

**Issue by divs1210** [matthiask/plata#73]
Hey! How can I add more types of discounts to my app without incurring downtime?
(because i'll have to add code to `CONFIG_OPTIONS` in `plata.discount.models`)

**Comment by matthiask** [comment]
You should probably do it this way (appending to `Discount.CONFIG_OPTIONS`):

https://github.com/matthiask/plata-options-product/blob/master/options_product/discount.py

The calls to `explicit_products` and `only_categories` should be placed in a models file; maybe AppConfig also works.
