### ISSUE TITLE
Take over the maintenance of this project

### ISSUE THREAD

**Issue by matthiask** [matthiask/plata#84]
Hi @fiee

I've only now become aware of your actively maintained fork of Plata. It's great that you're doing this! Do you want to share maintenance? A new, stable release would be awesome!

If yes, I'll happily give you access to the repo and PyPI.

**Comment by fiee** [comment]
Hallo Matthias!
Meine beiden Projekte mit Plata hängen schon ziemlich lange, und ich weiß nicht, ob ich das ganze System jemals zum Laufen bekomme, da ist mir immer noch zu viel unklar, auch wenn ich schon manches verstanden habe...
Wenn du für ein paar Fragen ansprechbar wärst, kann ich gerne die Rolle des Maintainers übernehmen. Große Aktivität werde ich allerdings voraussichtlich nicht an den Tag legen, außer dass ich ein- bis zweimal im Jahr nötige Anpassungen an die aktuelle Django-Version mache.
Herzliche Grüße, Hraban
PS: Danke für FeinCMS!

**Comment by matthiask** [comment]
Alles klar :)

Wir haben auch noch zwei Projekte mit plata am laufen, aber ja. Die Weiterentwicklung ist nicht grad mit Siebenmeilenstiefeln vorwärts gegangen. Ich melde mich aber sicher nicht ab!

**Comment by matthiask** [comment]
So. Tests laufen wieder durch. Style Checks auch. 

Habe ein altes Projekt mal auf Django 1.8 angehoben. Django 1.11 hoffentlich bald...

**Comment by matthiask** [comment]
Wir haben immer noch Projekte online mit Plata, und ich möchte diese auf neuere Django Versionen anheben. Auf 1.8 hoch hat gut geklappt. 1.11 oder 2.x wäre schon hübsch.

Es wäre eine gute Gelegenheit, den Tree etwas aufzuräumen, die vorhandenen Features auf Vordermann zu bringen, und dann Plata 2 zu veröffentlichen.

**Comment by fiee** [comment]
Meine beiden Projekte mit unvollständigem Plata laufen mit Django 1.11.9 und FeinCMS 1.13.5; könnte ich auch mal wieder updaten...

**Comment by matthiask** [comment]
Maintenance Effort teilen funktioniert ja schon.
