### ISSUE TITLE
plata.shop.actions.export_as_csv_action: Point users to xlsxdocuments' export_select instead?

### ISSUE THREAD

**Issue by matthiask** [matthiask/plata#85]
https://pypi.org/project/xlsxdocument/

Opinions?

cc @fiee

**Comment by fiee** [comment]
Never tried that. I’m only using https://pypi.org/project/xlwt/ in two projects, but it’s outdated.

**Comment by matthiask** [comment]
Less code means less to test, less to maintain.

And it's not really about adding features, but about replacing code that's being used in a single place with code that's used in many places.
